# Site settings
title: Personal Todo App
email: mark@markdejong.com
description: "This is a basic Todo application, where you can add, remove and highlight a specific item as done."
baseurl:
url: http://localhost:4000
api: http://localhost:5123/api/todos

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["README.md"]

sass:
  sass_dir:         _sass
  # style:            :compressed
